### ISSUE TITLE
METEOR M2 images

### ISSUE THREAD

**Issue by GlassesToCSharp** [filipsPL/autowx2#102]
Hi all,

I'm getting NOAA images absolutely fine, but I'm getting METEOR images like so:

<img src="https://user-images.githubusercontent.com/42772107/89729873-ac77b380-da31-11ea-99e0-48d1afe40daf.jpg" height="200px"/> <img src="https://user-images.githubusercontent.com/42772107/89729896-d6c97100-da31-11ea-8721-cd5752a77d2c.jpg" height="200px"/>

Does anyone have any suggestions as to why this is happening and how I can improve this? [This reddit post](https://www.reddit.com/r/amateurradio/comments/67gpsm/meteor_m2_receiving_images_with_black_stripes/) suggest removing `lna4all`, but I can't find any usage of it.

I'm using this [TA-1 cross-dipole antenna](https://www.wimo.com/en/ta-1) to receive my signals, which is connected to my RTL-SDR, which is connected to my RaspberryPi.

TIA!

**Comment by SA7BNT** [comment]
Please post your config for M2

Best

**Comment by ThomasBartleet** [comment]
@SA7BNT Wow, what a quick response!

There are are few config file for M2: `M2-1-72k.cgf`, `M2-2-72k.cfg`, and `M2-2-80k.cfg`. Below is the contents of `M2-2-80k.cfg`:
```
############## mlrpt RUNTIME CONFIGURATION FILE: mlrptrc ########
#                                                                 #
# PLEASE NOTE! In order to keep the parser for this file simple,  #
# the runtime configuration entries below must all be present and #
# in the order presented, since they are all read-in in a fixed   #
# sequence. Blank lines or those starting with a # (comments etc) #
# are ignored.                                                    #
#                                                                 #
# Please check ALL ENTRIES and EDIT as needed!!                   #
#                                                                 #
###################################################################
#
####### SDR RECEIVER CONFIGURATION #######
# SDR Receiver type to be used for satellite reception.
# Available support is for RTL-SDR and  AIRSPY R2 and Mini
# Default is to use an RTL-SDR device with librtlsdr.
RTL-SDR
#AIRSPY
#
# Device Index. Default is 0 (use first SDR device).
# Maximum value is 8 for data sanity checking.
0
#
# SDR Receiver's I/Q Sample Rate S/s.
# THIS DEPENDS ON THE SDR RX IN USE.
# For RTL-SDR,      288000 S/s.
# For Airspy R2,    2500000 S/s.
# For Airspy Mini,  3000000 S/s.
288000
#2500000
#3000000
#
# Low Pass Roofing Filter Bandwidth. This should be more than
# 100000 Hz for sanity checking. Default is 110000 Hz
# and this is probably the narrowest useable bandwidth.
110000
#
# Manual Tuner Gain setting. If 0, then Auto AGC will be used.
# Value range is 0 - 100% and default is 95% (manual AGC used).
95
#
# Synthesizer Frequency Error correction factor. This is in
# ppm (parts per million) but it has to be an integer number.
# Maximum +/- value for sanity checks is 100.
0
#
####### Mlrpt operational parameters #######
#
# Satellite Transmitter Frequency in kHz (default Meteor M2)
137900
#
# Duration in seconds of image decoding operation (900). This
# is usually to long (15 min) unless a high gain rotating
# directional antenna is used. This value can be changed here
# or using the "Operation Timer" menu item in the pop-up menu.
900
#
####### LRPT Demodulator Parameters #######
#
# RRC (Raised Root Cosine) Filter Order. Default is 32.
32
#
# RRC Filter alpha factor. Default is 0.6 and need not be changed.
0.6
#
# Initial Costas PLL Loop Bandwidth in Hz. Default is 200. May be
# experimented with to give best compromise between early PLL lock
# and stray locks.
100
#
# Costas PLL In-Lock Phase Error Threshold. Below this the PLL
# will be in Locked mode. The PLL Unlocked Threshold will be
# set at +5% above this. The actual value will depend on Receiver
# noise levels and antenna performance. It should be selected so
# that the PLL Locked indication should just be off with no signal.
0.80
#
# Modulation Mode: 1 = QPSK  2 = DOQPSK  3 = IDOQPSK
3
#
# Symbol Rate of the (O)QPSK Transmission in Sy/s. Default is 72000.
80000
#
# Demodulator Interpolation factor. Default is 4 and need not be changed.
4
#
####### LRPT Decoder Parameters #######
# Decoded Image Output Mode:
# 1 = Output a combined APID channels pseudo-colorized image.
# 2 = Output individual monochrome images of APID channels.
# 3 = Output both channel images and pseudo color combination.
3
#
# File type for saving monochrome channel (APD) images ONLY!
# 1 = Save as jpeg. 2 = Save as PGM file. 3 = Save as both.
1
#
# JPEG compression quality factor (percent). Default is 85 %
85
#
# Enable saving of Raw (unprocessed) Images as well.
# 0 = no, 1 = yes.
0
#
# Image Normalization (Stretches image contrast). 0 = no, 1 = yes.
1
#
# Contrast Limited Adaptive Histogram Equalization (CLAHE).
# Enhances Regional Contrast of images very effectively.
# Will only have effect if the above option is also enabled.
# 0 = no, 1 = yes.
1
#
# Rectify images: Corrects geometric distortion of images caused
# by the curvature of Earth and Tangential distortion.
# 0 = no, 1 = Use the W2RG algorithm, 2 = Use the 5B4AZ algorithm.
1
#
# Pseudo-colorize images: Does some speculative colorization of the
# combined pseudo-color image. 0 = no, 1 = yes.
1
#
# Image APID's (channels) for red, green, blue used for combined
# pseudo-color image.
# Red APID (mlrpt Channel 0)
66
#
# Green APID (mlrpt Channel 1)
65
#
# Blue APID (mlrpt Channel 2)
64
#
# APIDs of images to invert their palette. This is normally useful
# for the Infrared images were cold is dark and hot is white. There
# should be three entries and 0 per place will disable this option
# for the entry.
67, 68, 69
#
# Range of pixel values to use when combining channels, to
# produce a reasonable color balance in the combined color
# image. Values must be between 0 and 255.
#
# For the Red Channel
0-230
#
# For the Green Channel
0-255
#
# For the Blue Channel
60-255
#
# When using the optional Pseudo-colorize function of mlrpt,
# the pixel values of the Blue channel image are increased
# so that they are in the range specified below. This helps
# because Histogram Equalization darkens the parts of the
# Blue Channel image that are watery areas (seas or lakes).
#
# Blue Channel minimum pixel value. Must be between 0-255.
# It is also the Blue Channel pixel value below which pixel
# values are mapped into the range between these two values.
60
#
# Blue Channel maximum pixel value when mapping pixel values
# into the range between these two values. Must be higher
# than the above minimum but less than 255.
80
#
# Blue channel cloudy area pixel value threshold. In pseudo-
# colorize mode, pixels with a value higher than this will be
# assumed to be cloudy areas and the RGB values in the combo
# color image will be made all equal to the blue channel pixels
210
#
# Directory to save received images in. Normally it would be
# /home/<user>/mlrpt/images/ if Default is entered here. Else
# the specified directory will be used. Maximum 80 characters.
Default (/home/<user>/mlrpt/images/)
#/var/lrpt/images/
#
```

**Comment by SA7BNT** [comment]
> @SA7BNT Wow, what a quick response!
> 
> There are are few config file for M2: `M2-1-72k.cgf`, `M2-2-72k.cfg`, and `M2-2-80k.cfg`. Below is the contents of `M2-2-80k.cfg`:
> 
> ```
> ############## mlrpt RUNTIME CONFIGURATION FILE: mlrptrc ########
> #                                                                 #
> # PLEASE NOTE! In order to keep the parser for this file simple,  #
> # the runtime configuration entries below must all be present and #
> # in the order presented, since they are all read-in in a fixed   #
> # sequence. Blank lines or those starting with a # (comments etc) #
> # are ignored.                                                    #
> #                                                                 #
> # Please check ALL ENTRIES and EDIT as needed!!                   #
> #                                                                 #
> ###################################################################
> #
> ####### SDR RECEIVER CONFIGURATION #######
> # SDR Receiver type to be used for satellite reception.
> # Available support is for RTL-SDR and  AIRSPY R2 and Mini
> # Default is to use an RTL-SDR device with librtlsdr.
> RTL-SDR
> #AIRSPY
> #
> # Device Index. Default is 0 (use first SDR device).
> # Maximum value is 8 for data sanity checking.
> 0
> #
> # SDR Receiver's I/Q Sample Rate S/s.
> # THIS DEPENDS ON THE SDR RX IN USE.
> # For RTL-SDR,      288000 S/s.
> # For Airspy R2,    2500000 S/s.
> # For Airspy Mini,  3000000 S/s.
> 288000
> #2500000
> #3000000
> #
> # Low Pass Roofing Filter Bandwidth. This should be more than
> # 100000 Hz for sanity checking. Default is 110000 Hz
> # and this is probably the narrowest useable bandwidth.
> 110000
> #
> # Manual Tuner Gain setting. If 0, then Auto AGC will be used.
> # Value range is 0 - 100% and default is 95% (manual AGC used).
> 95
> #
> # Synthesizer Frequency Error correction factor. This is in
> # ppm (parts per million) but it has to be an integer number.
> # Maximum +/- value for sanity checks is 100.
> 0
> #
> ####### Mlrpt operational parameters #######
> #
> # Satellite Transmitter Frequency in kHz (default Meteor M2)
> 137900
> #
> # Duration in seconds of image decoding operation (900). This
> # is usually to long (15 min) unless a high gain rotating
> # directional antenna is used. This value can be changed here
> # or using the "Operation Timer" menu item in the pop-up menu.
> 900
> #
> ####### LRPT Demodulator Parameters #######
> #
> # RRC (Raised Root Cosine) Filter Order. Default is 32.
> 32
> #
> # RRC Filter alpha factor. Default is 0.6 and need not be changed.
> 0.6
> #
> # Initial Costas PLL Loop Bandwidth in Hz. Default is 200. May be
> # experimented with to give best compromise between early PLL lock
> # and stray locks.
> 100
> #
> # Costas PLL In-Lock Phase Error Threshold. Below this the PLL
> # will be in Locked mode. The PLL Unlocked Threshold will be
> # set at +5% above this. The actual value will depend on Receiver
> # noise levels and antenna performance. It should be selected so
> # that the PLL Locked indication should just be off with no signal.
> 0.80
> #
> # Modulation Mode: 1 = QPSK  2 = DOQPSK  3 = IDOQPSK
> 3
> #
> # Symbol Rate of the (O)QPSK Transmission in Sy/s. Default is 72000.
> 80000
> #
> # Demodulator Interpolation factor. Default is 4 and need not be changed.
> 4
> #
> ####### LRPT Decoder Parameters #######
> # Decoded Image Output Mode:
> # 1 = Output a combined APID channels pseudo-colorized image.
> # 2 = Output individual monochrome images of APID channels.
> # 3 = Output both channel images and pseudo color combination.
> 3
> #
> # File type for saving monochrome channel (APD) images ONLY!
> # 1 = Save as jpeg. 2 = Save as PGM file. 3 = Save as both.
> 1
> #
> # JPEG compression quality factor (percent). Default is 85 %
> 85
> #
> # Enable saving of Raw (unprocessed) Images as well.
> # 0 = no, 1 = yes.
> 0
> #
> # Image Normalization (Stretches image contrast). 0 = no, 1 = yes.
> 1
> #
> # Contrast Limited Adaptive Histogram Equalization (CLAHE).
> # Enhances Regional Contrast of images very effectively.
> # Will only have effect if the above option is also enabled.
> # 0 = no, 1 = yes.
> 1
> #
> # Rectify images: Corrects geometric distortion of images caused
> # by the curvature of Earth and Tangential distortion.
> # 0 = no, 1 = Use the W2RG algorithm, 2 = Use the 5B4AZ algorithm.
> 1
> #
> # Pseudo-colorize images: Does some speculative colorization of the
> # combined pseudo-color image. 0 = no, 1 = yes.
> 1
> #
> # Image APID's (channels) for red, green, blue used for combined
> # pseudo-color image.
> # Red APID (mlrpt Channel 0)
> 66
> #
> # Green APID (mlrpt Channel 1)
> 65
> #
> # Blue APID (mlrpt Channel 2)
> 64
> #
> # APIDs of images to invert their palette. This is normally useful
> # for the Infrared images were cold is dark and hot is white. There
> # should be three entries and 0 per place will disable this option
> # for the entry.
> 67, 68, 69
> #
> # Range of pixel values to use when combining channels, to
> # produce a reasonable color balance in the combined color
> # image. Values must be between 0 and 255.
> #
> # For the Red Channel
> 0-230
> #
> # For the Green Channel
> 0-255
> #
> # For the Blue Channel
> 60-255
> #
> # When using the optional Pseudo-colorize function of mlrpt,
> # the pixel values of the Blue channel image are increased
> # so that they are in the range specified below. This helps
> # because Histogram Equalization darkens the parts of the
> # Blue Channel image that are watery areas (seas or lakes).
> #
> # Blue Channel minimum pixel value. Must be between 0-255.
> # It is also the Blue Channel pixel value below which pixel
> # values are mapped into the range between these two values.
> 60
> #
> # Blue Channel maximum pixel value when mapping pixel values
> # into the range between these two values. Must be higher
> # than the above minimum but less than 255.
> 80
> #
> # Blue channel cloudy area pixel value threshold. In pseudo-
> # colorize mode, pixels with a value higher than this will be
> # assumed to be cloudy areas and the RGB values in the combo
> # color image will be made all equal to the blue channel pixels
> 210
> #
> # Directory to save received images in. Normally it would be
> # /home/<user>/mlrpt/images/ if Default is entered here. Else
> # the specified directory will be used. Maximum 80 characters.
> Default (/home/<user>/mlrpt/images/)
> #/var/lrpt/images/
> #
> ```

OK, you may just use M2-1-72k.cgf. M2-2* is already dead :( 
Here is my conf

[Meteor_M2_conf.txt](https://github.com/filipsPL/autowx2/files/5047275/Meteor_M2_conf.txt)

Here can you get the some more information
http://happysat.nl/Meteor/html/Meteor_Status.html?fbclid=IwAR2HdqUTTYDDi3unstM7hziPGa105udOXDn9GIim6wFYNlfIFPDv5uvaIW8

**Comment by ThomasBartleet** [comment]
Ah shoot! Ok, I will try with your config. Many thanks! The next fly-over is at 8pm (BST), so I will wait to see how that works out.

**Comment by SA7BNT** [comment]
You welcome!! ;)

**Comment by SA7BNT** [comment]
BTW @ThomasBartleet my minElev = 30
For me is all under 30° is crap

**Comment by ThomasBartleet** [comment]
Hi @SA7BNT , I tried with your config file, but I still got some the following picture:
<img src="https://user-images.githubusercontent.com/42772107/89772361-c977b980-daf9-11ea-834d-a49e76739a31.jpg" height="200px"/>

I have my min elavation at 50 degrees.

What is the main cause for so much data loss? Do I need an amplifier between my antenna and my SDR? Increase the gain? Or is it just my antenna that is just pants?

My next fly-over is now not until tomorrow morning. I'll record the audio and run some tests on the recorded audio. Maybe then I'll be able to tweak the configuration to best suit for me. Or maybe I'll find there's an issue somewhere else.

**Comment by ThomasBartleet** [comment]
It looks like there might be some insight over on [Reddit](https://www.reddit.com/r/RTLSDR/comments/8xlhrq/can_anyone_help_decoding_my_meteor_m2_recording/). I'll have a look at this at some point, but it seems to be hardware-related issues on the receiving end. In other words, my equipment is lacking. Thoughts?

**Comment by SA7BNT** [comment]
@ThomasBartleet i´m just running an SDR-RTL.com 50m 50 Ohm Coax (Aircell7) and the antenna is a homemade turnstile on hardware side. Is the RTL-SDR a known like SDR-COM or Nooelec?? Is the RTL-SDR running in idle time?? Asking because if not the RTL-SDR  getting cold and then the ppm will drift away. Hope you understand. 
BTW you can also catch me on Telegram if you are interested. @SA7BNT 
What language are you?

Best

**Comment by ThomasBartleet** [comment]
Hi @SA7BNT !
Sorry for getting back to you late! I've been really busy with other commitments and finding alternatives to MLRPT. It turns out there are indeed other alternatives, especially for the Raspberry Pi. Below is an image from yesterday evening:
<img src="https://user-images.githubusercontent.com/42772107/90732187-a3ed6b80-e2c2-11ea-8ad7-99f5f1adc784.png" width="200px"/>

I've got another pass later this morning, which should get me a better day-time picture.

From this, it looks like that the MLRPT that AutoWX2 uses is too heavy for the RaspberryPi. I ended up using [`meteor_demod`](https://github.com/dbdexter-dev/meteor_demod) and [`meteor_decoder`](https://github.com/artlav/meteor_decoder), and I re-wrote the `meteor_record.sh` script that allows the RPi to get the image above. Maybe this needs a PR? I would have thought if it can run on the RPi, it can run on bigger (and better) machines?

Just to answer your questions: I am using a NooElec dongle, and the program does not run anything while waiting for passes (maybe the PPM does drift a bit?).

**Comment by ThomasBartleet** [comment]
Just to show the effectiveness of the changes I made, below is the image from this morning:
<img src="https://user-images.githubusercontent.com/42772107/90793076-2e55bf80-e303-11ea-8429-3c97235b2a97.png" width="200px"/>

This beats the original images I was getting (example in the initial comments way above) using the current MLRPT. @filipsPL , is this worth looking into, or is it too much of an isolated case?

**Comment by 0nnyx** [comment]
@ThomasBartleet Could you share your meteor script & config ? Also running on Rpi and would like to give meteor another try.

**Comment by ThomasBartleet** [comment]
@0nnyx Sure! You can find the actual processing code on my fork over at https://github.com/ThomasBartleet/autowx2/pull/1. You'll find I've retained a similar structure as the NOAA processing files.

For additional features, I've had to modify the actual `meteor.conf` file a little bit. It should be self-explanatory though:
```
#
# meteor m2 module configuration file
#

medetExec="$baseDir/medet/medet_arm"

# directory with meteor stuff
meteorDir="$recordingDir/meteor"

# directory of meteor recordings
rootMeteorRecDir="$meteorDir/rec"
recdir="$rootMeteorRecDir/"$(date +"%Y/%m/%d")

# directory where the images finally will go
rootMeteorImgDir="$meteorDir/img"
imgdir="$rootMeteorImgDir/"$(date +"%Y/%m/%d")

# Option to save images as PNG or JPG (if neither, defaults to JPG)
imageExtension="png"
# imageExtension="jpg"

# resize images to the given size to avoid growing of the repository; in px
# resizeimageto=1024

# Shall we remove the audio and processing files? If not, comment out below
# or leave blank.
removeFiles="true"

# The images stored take up room, as well as the recordings (if storing recordings). Over time,
# this data might not be necessary, so it should to be removed. Store the data for a specificed
# number of days (set to 0 for "do not remove").
keepDataForDays=7
```

Just a note, I'm not storing the images for each individual channel. The script only gets the image from combining the channels.

**Comment by 0nnyx** [comment]
Thanks, will see how it performs :) Your Meteor branch also has that nice script for removing files older than X days, which is a must on Rpi with limited SD space.

**Comment by 0nnyx** [comment]
@ThomasBartleet The default RGB values for medet on your repo systematically generate very red images. I guess you found a way to improve that. Just in case, I altered a bit the meteor_process.sh to have false colored during daylight (64 & 65 only) and infrared (68 only) when sun is down:
```
# Decide the file and make image.
if [ -f $decodedAudioFile ]; then
    echo "I got a successful ${3}.dec file. Creating false color image"
    if [ $(date +%H) -lt 17 ]; then
      ./meteor_decoder/medet $decodedAudioFile "${imageFile}-122" -r 65 -g 65 -b 64 -d
    else
      ./meteor_decoder/medet $decodedAudioFile "${imageFile}-122" -r 68 -g 68 -b 68 -d
    fi
    convert "${imageFile}-122.bmp" "${imageFile}.jpg"
    if [ -f "${imageFile}.jpg" ]; then
      rm "${imageFile}-122.bmp"
    fi
```

**Comment by ThomasBartleet** [comment]
@0nnyx Yes, I realised they were a bit red-ish, and I was going to look into it, but never got around it. Your bit of code looks promising! It'll definitely help get night images as well as day images. I've got a pass tomorrow morning, so I will see how that works out.

Ultimately, maybe we can use some open-source sunrise/sunset API (for example, [this one](https://sunrise-sunset.org/api)) to determine when a user will be in the dark when the M2 satellite is overhead (`#TODO`).

**Comment by filipsPL** [comment]
> Ultimately, maybe we can use some open-source sunrise/sunset API (for example, [this one](https://sunrise-sunset.org/api)) to determine when a user will be in the dark when the M2 satellite is overhead (`#TODO`).

We may use a self hosted solution, such as astral:
https://pypi.org/project/astral/1.2/
https://astral.readthedocs.io/en/latest/#sun

**Comment by ploeffler** [comment]
maybe an offline-solution for that would be better: predict can do that

regards peter
--
Disclaimer: May be opened and read by the NSA, CIA, GCHQ, KGB, BND, and
whoever else it may NOT concern.


Am Di., 16. März 2021 um 08:52 Uhr schrieb filips ***@***.***

**Comment by 0nnyx** [comment]
Meteor will only show visible channels until September - see http://happysat.nl/Meteor/html/Meteor_Status.html - so best to keep medet with the default RGB values 66 65 64 and expect all evening images to be useless for the next 5 months.
Would be good to have autowx2_conf with a priority based on the time of the day

**Comment by ThomasBartleet** [comment]
@0nnyx Good shout! That should make things much easier (and better coloured) for now.

**Comment by 0nnyx** [comment]
In case anyone still has Meteor in their wanted passes, only the new N2-3 satellite is active - see happysat.nl page for details.
Note the antenna of this new satellite didn't manage to deploy fully. Therefore recordings won't be as successful as old Meteor.

In terms of decoding, mlrpt software is outdated, extremely slow (taking ~1hour on Pi3) and doesn't produce the best results.
Best to use Satdump from https://github.com/SatDump/SatDump or meteor_demod + meteor_decode from https://github.com/dbdexter-dev. Both take ~5min on Pi3.

Satdump produces the best results but isn't suited for automated gallery processing. 
CLI examples (GUI also available) : 
```
satdump meteor_m2-x_lrpt baseband <wav file path> <output directory> (for 72k)
satdump meteor_m2-x_lrpt_80k baseband <wav file path> <output directory> (for 80k)
```
Meteor_demod & decode is easy to integrate for automated gallery.
- 72k requires these commands : 
```
meteor_demod -B -m oqpsk -o $demodulatedAudioFile $normalisedAudioFile
meteor_decode -B -d -q -o "${imageFile}.bmp" $demodulatedAudioFile
```
- 80k requires those commands : 
```
meteor_demod -B -m oqpsk -r 80000 -o $demodulatedAudioFile $normalisedAudioFile
meteor_decode -B -d -i -q -o "${imageFile}.bmp" $demodulatedAudioFile
```

**Comment by OK1SLM** [comment]
Does anyone have the best current settings on Meteor?

**Comment by 0nnyx** [comment]
> Does anyone have the best current settings on Meteor?

Don't really understand your question... Read my post above first.
Current (and past months) settings for N2-3 are 72K for symbol rate and frequency of 137900000Hz.
Same situation as before regarding image retrieval depending on software : satdump > meteor_demod + meteor_decode > mlrpt
If you have an external antenna on your roof, you can probably get decent images despite the bad antenna deployment.
Having my antenna stuck to a window in the attic, I rarely get any good image unlike the previous dead meteor - attaching samples.
Dead M2-1 : 
![20220917-0801_METEOR-M2-1](https://github.com/filipsPL/autowx2/assets/54419678/80dec3fd-5fcf-404e-ad20-a68e3d6c309a)

Current M2-3 : 
![20240111-1005_METEOR-M2-3](https://github.com/filipsPL/autowx2/assets/54419678/422a43d6-ed0d-43f6-a1e5-5fa8a70aa351)

**Comment by OK1SLM** [comment]
Sorry, I didn't notice the new post.
Can you give me the cfg mrlpt ?

**Comment by OK1SLM** [comment]
HI Onnyx,
I installed your modified version and I want to ask if receiving images from Meteor M2-3 is functional?
https://www.ok1slm.cz/

**Comment by OK1SLM** [comment]
I have a QFH antenna with a preamplifier, but the program keeps restarting when I receive Meteor, I have no idea if I should edit something in the script.

**Comment by 0nnyx** [comment]
> I have a QFH antenna with a preamplifier, but the program keeps restarting when I receive Meteor, I have no idea if I should edit something in the script.

Here are my scripts, requiring meteor_demod + meteor_decode from https://github.com/dbdexter-dev
I won't help you further though.
Use the Satdump windows installer with the GUI if the CLI automated linux is too complex.

**modules/meteor-m2/meteor_record.sh**
```
#!/bin/bash
startT=$(date +%H%M -d "$DATE + 1 min" -u)
stopT=$(date +%H%M -d "$DATE + $duration sec" -u)
durationMin=$(bc <<< "$duration/60 +2")

#
# recording
#
echo "$startT-$stopT, duration: $durationMin min"
# $1 = Satellite Name
# $2 = Frequency
# $3 = FileName base
# $4 = TLE File
# $5 = EPOC start time
# $6 = Time to capture
# $7 = Satellite max elevation

echo "Satellite Name=$1"
echo "Frequency=$2"
echo "FileName base=$3"
echo "TLE File=$4"
echo "EPOC start time=$5"
echo "Time to capture=$6"
echo "Satellite max elevation=$7"

rawDirectory="${recdir}/raw"
rawAudioFile="${rawDirectory}/${3}.wav"
processedFile="${recdir}/${3}"
normalisedAudioFile="${processedFile}.wav"
demodulatedAudioFile="${processedFile}.qpsk"
decodedAudioFile="${processedFile}.dec"

# Create folders if they don't exist
mkdir -p $rawDirectory

echo "Starting rtl_fm record"
timeout ${6} rtl_fm -f ${2} -M raw -s 288k -g 49.6 -d 1 -A fast -F 9 -E dc -E deemp | sox -t raw -r 288k -c 2 -b 16 -e s - -t wav $rawAudioFile rate 96k

echo "Normalization in progress"
sox $rawAudioFile $normalisedAudioFile gain -n

# Remove the raw audio file. We don't need it anymore, as we can just
# use the normalised audio file.
rm "${recdir}/raw/${3}.wav"
```

**modules/meteor-m2/meteor_process.sh**
```
#!/bin/bash

processedFile="${recdir}/${1}"
imageFile="${imgdir}/${1}"
normalisedAudioFile="${processedFile}.wav"
demodulatedAudioFile="${processedFile}.qpsk"
decodedAudioFile="${processedFile}.dec"


# Demodulate the audio file
echo "Demodulation in progress (QPSK)"
meteor_demod -B -m oqpsk -o $demodulatedAudioFile $normalisedAudioFile
#meteor_demod -B -m oqpsk -r 80000 -o $demodulatedAudioFile $normalisedAudioFile

# Decode th demoodulated file
echo "Decoding in progress (QPSK to BMP)"

meteor_decode -B -d -q -o "${imageFile}.bmp" $demodulatedAudioFile
#meteor_decode -B -d -i -q -o "${imageFile}.bmp" $demodulatedAudioFile
convert -quality 95 "${imageFile}.bmp" "${imageFile}.jpg"
    if [ -f "${imageFile}.jpg" ]; then
      rm "${imageFile}.bmp"
    fi
else
    echo "[DEBUG] Meteor Decoding failed, either a bad pass/low SNR or a software problem"
fi

#if [ "${removeFiles}" -ne "" ]; then
rm $normalisedAudioFile
rm $demodulatedAudioFile
#fi
```

**Comment by 0nnyx** [comment]
For anyone interested, a new meteor satellite METEOR-M2-4 has been launched and is currently in testing phase.
It's very possible that M2-4 had a proper antenna deployment and would produce good images unlike M2-3.
Since happysat website is down, you can get more info at https://usradioguy.com/meteor-satellite/

**Comment by SA7BNT** [comment]
> > I have a QFH antenna with a preamplifier, but the program keeps restarting when I receive Meteor, I have no idea if I should edit something in the script.
> 
> Here are my scripts, requiring meteor_demod + meteor_decode from https://github.com/dbdexter-dev I won't help you further though. Use the Satdump windows installer with the GUI if the CLI automated linux is too complex.
> 
> **modules/meteor-m2/meteor_record.sh**
> 
> ```
> #!/bin/bash
> startT=$(date +%H%M -d "$DATE + 1 min" -u)
> stopT=$(date +%H%M -d "$DATE + $duration sec" -u)
> durationMin=$(bc <<< "$duration/60 +2")
> 
> #
> # recording
> #
> echo "$startT-$stopT, duration: $durationMin min"
> # $1 = Satellite Name
> # $2 = Frequency
> # $3 = FileName base
> # $4 = TLE File
> # $5 = EPOC start time
> # $6 = Time to capture
> # $7 = Satellite max elevation
> 
> echo "Satellite Name=$1"
> echo "Frequency=$2"
> echo "FileName base=$3"
> echo "TLE File=$4"
> echo "EPOC start time=$5"
> echo "Time to capture=$6"
> echo "Satellite max elevation=$7"
> 
> rawDirectory="${recdir}/raw"
> rawAudioFile="${rawDirectory}/${3}.wav"
> processedFile="${recdir}/${3}"
> normalisedAudioFile="${processedFile}.wav"
> demodulatedAudioFile="${processedFile}.qpsk"
> decodedAudioFile="${processedFile}.dec"
> 
> # Create folders if they don't exist
> mkdir -p $rawDirectory
> 
> echo "Starting rtl_fm record"
> timeout ${6} rtl_fm -f ${2} -M raw -s 288k -g 49.6 -d 1 -A fast -F 9 -E dc -E deemp | sox -t raw -r 288k -c 2 -b 16 -e s - -t wav $rawAudioFile rate 96k
> 
> echo "Normalization in progress"
> sox $rawAudioFile $normalisedAudioFile gain -n
> 
> # Remove the raw audio file. We don't need it anymore, as we can just
> # use the normalised audio file.
> rm "${recdir}/raw/${3}.wav"
> ```
> 
> **modules/meteor-m2/meteor_process.sh**
> 
> ```
> #!/bin/bash
> 
> processedFile="${recdir}/${1}"
> imageFile="${imgdir}/${1}"
> normalisedAudioFile="${processedFile}.wav"
> demodulatedAudioFile="${processedFile}.qpsk"
> decodedAudioFile="${processedFile}.dec"
> 
> 
> # Demodulate the audio file
> echo "Demodulation in progress (QPSK)"
> meteor_demod -B -m oqpsk -o $demodulatedAudioFile $normalisedAudioFile
> #meteor_demod -B -m oqpsk -r 80000 -o $demodulatedAudioFile $normalisedAudioFile
> 
> # Decode th demoodulated file
> echo "Decoding in progress (QPSK to BMP)"
> 
> meteor_decode -B -d -q -o "${imageFile}.bmp" $demodulatedAudioFile
> #meteor_decode -B -d -i -q -o "${imageFile}.bmp" $demodulatedAudioFile
> convert -quality 95 "${imageFile}.bmp" "${imageFile}.jpg"
>     if [ -f "${imageFile}.jpg" ]; then
>       rm "${imageFile}.bmp"
>     fi
> else
>     echo "[DEBUG] Meteor Decoding failed, either a bad pass/low SNR or a software problem"
> fi
> 
> #if [ "${removeFiles}" -ne "" ]; then
> rm $normalisedAudioFile
> rm $demodulatedAudioFile
> #fi
> ```

Hey 0nnyx,

did you get img with this setup and autowx2 ?
I´m running your record&process.sh but it is still not possible to get some img

Best

**Comment by OK1SLM** [comment]
I'm sad that this project is dead. I switched to the https://github.com/jekhokie/raspberry-noaa-v2 project

**Comment by filipsPL** [comment]
The project is not dead. The issue with recording and interpreting METEOR (or any other signal) is out of the scope of this project and the developer.
