### ISSUE TITLE
Use noaa-apt instead of wxtoimg

### ISSUE THREAD

**Issue by thecivvie** [filipsPL/autowx2#109]
I recently came across the git mentioned in the topic. seems to do everything that wxtoimg does. I am only testing it now so not sure what the images are truly like. Will post one once I do but seems popular on github

**Comment by thecivvie** [comment]
![NOAA1920210119-172703-noaa-apt](https://user-images.githubusercontent.com/34013299/105073918-9f9ac980-5a7f-11eb-9bba-1be0e8f04106.png)
Not a great image as it was a low pass

**Comment by filipsPL** [comment]
Thanks for post. We look forward for your long-term observation. You can also send some good images here.

**Comment by filipsPL** [comment]
Tested, but so far the results are slightly worse than wxtoimg:

![obraz](https://user-images.githubusercontent.com/11406606/218298133-57e661f5-5085-4af7-97c8-858a1d8e71ea.png)

I will keep track of this software, but now closing the issue. Thanks for reporting!
