### ISSUE TITLE
UserWarning when using genpasstable.py

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#18]
sa7bnt@owncloud:~/autowx2$ python genpasstable.py 
 1. discard NOAA 19, keep ISS
 1. discard NOAA 15, keep ISS
 1. discard NOAA 15, keep ISS
 1. discard NOAA 18, keep ISS
 1. discard NOAA 18, keep ISS
/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
  	 satellite	           start	dur MM:SS	peak	 az	    az	      freq	        process with
  1	   NOAA 19	2018-10-03 12:58	    14:11	  35	 60	 NE↗	 137100000	modules/noaa/noaa.sh
  2	   NOAA 19	2018-10-03 14:38	    14:47	  47	260	WSW←↙	 137100000	modules/noaa/noaa.sh
  3	       ISS	2018-10-03 15:21	    09:57	  50	161	SSE↓↘	 143625000	modules/iss/iss_voice.sh
  4	   NOAA 15	2018-10-03 16:23	    14:39	  87	 72	ENE→↗	 137620000	modules/noaa/noaa.sh
  5	       ISS	2018-10-03 16:57	    10:08	  81	180	  S↓	 143625000	modules/iss/iss_voice.sh
  6	   NOAA 18	2018-10-03 17:05	    14:45	  46	 64	 NE↗	 137912500	modules/noaa/noaa.sh
  7	       ISS	2018-10-03 18:33	    09:57	  46	200	  S↓	 143625000	modules/iss/iss_voice.sh
  8	   NOAA 18	2018-10-03 18:46	    14:36	  35	263	WSW←↙	 137912500	modules/noaa/noaa.sh

**Comment by filipsPL** [comment]
Fixed in commit 5434aa2. Let me know it the program persist?
