### ISSUE TITLE
Possible to make a log file

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#20]
Is it possible to get some log file?? Have not seen it in the config. Would be nice. Or something like e-mail notify if something goes wrong.

**Comment by filipsPL** [comment]
Sending emails is quite tricky for many reasons. But logfile is definitely doable!

**Comment by filipsPL** [comment]
And what about a simple webserver you can connect and see what is going on?

**Comment by SA7BNT** [comment]
Should be a great feature. Looking forward to see the result ;)

**Comment by filipsPL** [comment]
As for now f4308aa contains the logging capabilities. Just edit the `logging` variable in the config file (or set to `False` to disable logging).

**Comment by filipsPL** [comment]
Good! Thanks for testing!
