### ISSUE TITLE
ISS recording problem

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#22]
Hey,
today i record the ISS and i observe that the record audio is to fast in its audio.
Here do you hear the Original voice of Alexander Gerst.
https://soundcloud.com/florian-df2et/ariss-school-conact-with-astro_alex-16102018-1028-utc
And here can you hear what autowx2 was recording.
[20181016-1207_ISS.mp3.zip](https://github.com/filipsPL/autowx2/files/2483352/20181016-1207_ISS.mp3.zip)
Something you have observed earlier??

Greeting 
Tim

**Comment by filipsPL** [comment]
I think this could be a matter of setting for mp3 encoding. I had a similar issues before, but I don't know how to fix it. I guess one need to play a little bit with mp3 encoding settings to get the proper speed/quality of the recording...

**Comment by SA7BNT** [comment]
I tried that and it sounds a lot better.
I add a k after -s 32 and add -l 0 in the front

timeout $duration rtl_fm -f $freq -M wbfm -g 49.6 -l 0 | lame -r -s 32k -m m - $recdir/$fileNameCore.mp3

**Comment by filipsPL** [comment]
I will update the scripts. Alternatively you can create a pull request with your version and I will merge it.

**Comment by filipsPL** [comment]
Thanks for fixing that!
