### ISSUE TITLE
No FM record

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#23]
Hey, 
wondering why the fm.sh is not recording.
Issue in the last commit??
If i running ./fm.sh with fix data in it there is no problem and 10sec. of rec are in the map.
![bildschirmfoto 2018-10-17 um 12 39 14](https://user-images.githubusercontent.com/35367117/47081084-f878b900-d209-11e8-89dd-2c25a6325f0b.png)

**Comment by filipsPL** [comment]
Thanks for fixing that in 1ce1386

**Comment by SA7BNT** [comment]
That was not the problem of that issue. Please read carefully my first post again

**Comment by filipsPL** [comment]
Should be fixed in bf821a4.

**Comment by filipsPL** [comment]
Great! Thanks for reporting!
