### ISSUE TITLE
Raspberry Pi / raspbian install script

### ISSUE THREAD

**Issue by filipsPL** [filipsPL/autowx2#29]
We need a tuned version of the `install.sh` dedicated to Raspberry Pi with Raspbian. Help needed! :sos:

**Comment by andrewl** [comment]
This PR works on an rpi zero w with rasbian installed:

https://github.com/filipsPL/autowx2/pull/36

**Comment by filipsPL** [comment]
Merged to f4ee8bf . Thanks! :+1:

**Comment by filipsPL** [comment]
Solved.
