### ISSUE TITLE
Tested same record config as NOAA

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#35]
Hey,
i should recommend to use the same recording config (noaa.sh) for ISS record.
Tested in the morning and was a working great.
[20181029-0542_ISS-SSTV.mp3.zip](https://github.com/filipsPL/autowx2/files/2524280/20181029-0542_ISS-SSTV.mp3.zip)
![iss1](https://user-images.githubusercontent.com/35367117/47635872-b7ac6880-db56-11e8-8cd0-df49fd95a814.jpg)

**Comment by SA7BNT** [comment]
I was just running the noaa.sh instead of the iss_voice.sh in the autowx2_config.py
See pic below
I did not convert to MP3. Took the wav from the noaa rec. map and run it in Multiscan 3B SSTV
https://www.qsl.net/kd6cji/
Was working absolutely great for me.

![bildschirmfoto 2018-10-29 um 14 49 53](https://user-images.githubusercontent.com/35367117/47654751-cfeaaa80-db8b-11e8-83a7-064dbc5d82a5.png)

![bildschirmfoto 2018-10-29 um 14 51 16](https://user-images.githubusercontent.com/35367117/47654108-6c13b200-db8a-11e8-88cf-4b1397f85111.png)
Unfortunately I live too far in the north and did not have a good elevation angle.
Here is one more ok pic. with ca 20 degree elevation. 
![iss2](https://user-images.githubusercontent.com/35367117/47654618-7bdfc600-db8b-11e8-9d65-b7fef173cd0e.jpg)

**Comment by filipsPL** [comment]
Ok, so then it depends on what you are trying to achieve. For recording of voice transmission, I would stay with mp3. For further decoding, like SSTV, wav is better. I will try to modify `iss.sh` to give these two options.

**Comment by filipsPL** [comment]
Fixed in 9abe2d9. Now there is an option in `iss_voice.sh` to select mp3 or wav destination. Please test! :wrench:

**Comment by filipsPL** [comment]
I have decided to do it another way: there are two separate modules:
- for recording wav file
- for recording mp3

and it is configured on the level of `autowx2_conf.py`.

changed in d22d4bc
