### ISSUE TITLE
iss_voice.sh in wav mode creating issue

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#37]
Just testing to record FOX1D in wav mode, but running in at some issue.
![bildschirmfoto 2018-11-01 um 10 12 33](https://user-images.githubusercontent.com/35367117/47843320-81255680-ddbf-11e8-948b-05fcd65cc9e9.png)
Edit: MP3 mode is working fine!!!

**Comment by filipsPL** [comment]
I have decided to do it another way: there are two separate modules:

- for recording wav file
- for recording mp3

and it is configured on the level of autowx2_conf.py.

changed in d22d4bc

Looking forward the results of tests!

**Comment by filipsPL** [comment]
Does it work or not? Can we close the issue? I suppose yes, but need a confirmation.

**Comment by SA7BNT** [comment]
Will let you know shortly
[https://twitter.com/RF2Space/status/1087767842785816576?s=19](url)

**Comment by SA7BNT** [comment]
Can be closed.
![iss_sstv_2_01_2019](https://user-images.githubusercontent.com/35367117/52071087-90fd3400-2582-11e9-96f5-114eae2a1ad8.jpg)
![iss_sstv_01_2019](https://user-images.githubusercontent.com/35367117/52071088-90fd3400-2582-11e9-92e3-788462d67daa.jpg)
![iss_sstv_01_2019_3](https://user-images.githubusercontent.com/35367117/52071091-90fd3400-2582-11e9-9579-67b1da3cf9c4.jpg)
