### ISSUE TITLE
Maybe a new module??

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#38]
Is it possible to add something like that to autowx2??
https://github.com/gvandela/MeteorRpiReceiver

**Comment by filipsPL** [comment]
Yes! Unfortunately I have no means to test it.

But it should simply work out of the box, just place the meteor's executable script's name in the `autowx2_conf.py` file in the `'processWith'` section and this should be it! I'm looking forward to results of tests!

**Comment by filipsPL** [comment]
see #46 and http://5b4az.org
