### ISSUE TITLE
The program stops after 1 pass

### ISSUE THREAD

**Issue by djmatsumatsu** [filipsPL/autowx2#67]
after recording one pass the script stops doing anything

**Comment by SA7BNT** [comment]
Some error´s in your log?
Please post the log

**Comment by djmatsumatsu** [comment]
Oh man i'm sorry, i was checking the wrong logs. Now i found out wxtoimgs
terms weren't accepted.... I'm sorry for taking you time

Op zo 10 feb. 2019 19:42 schreef SA7BNT <notifications@github.com:

**Comment by SA7BNT** [comment]
It´s OK
