### ISSUE TITLE
Error WSPR

### ISSUE THREAD

**Issue by OK1SLM** [filipsPL/autowx2#92]
OS Error during command: /home/pi/autowx2/bin/wspr.sh 2633 0  2020-02-09 19:33  
✖ OS Error: Permission denied 

Please help THX

**Comment by SA7BNT** [comment]
Please show ls -lisa /home/pi/autowx2/bin

**Comment by OK1SLM** [comment]
celkem 136
399358  4 drwxr-xr-x 5 pi   pi    4096 srp 22 19:00 .
399292  4 drwxr-xr-x 9 pi   pi    4096 úno  9 19:27 ..
399

**Comment by OK1SLM** [comment]
Thanks, I'm an idiot
